version: "3.8"

services:
  api:
    image: smtpbox
    container_name: smtpbox
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      HTTP_PORT: 8080
      SMTP_PORT: 1025
      SMTP_DOMAIN: "example.net"
    ports:
      - "8080:8080"
      - "1025:1025"
    networks:
      - dev_net

networks:
  dev_net:
